Repository openimsdk/open-im-sdk-reactnative, pull requests merged in 2024-01, with the labels that each got.

#15 update to 3.5.1
  android/build.gradle
  android/src/main/java/com/openimsdkrn/OpenImSdkRnModule.java
  android/src/main/java/com/openimsdkrn/listener/AdvancedMsgListener.java
  android/src/main/java/com/openimsdkrn/listener/OnConversationListener.java
  ios/OpenImSdkRn.m
  open-im-sdk-rn.podspec
Labels: size/M

#16 update function and add declaration
  android/src/main/java/com/openimsdkrn/OpenImSdkRnModule.java
  android/src/main/java/com/openimsdkrn/listener/SetCustomBusinessListener.java
  example/package-lock.json
  example/yarn.lock
  ios/OpenImSdkRn.m
  open-im-sdk-rn.d.ts
  package.json
Labels: size/XXL

#17 update uploadlog
  android/src/main/java/com/openimsdkrn/OpenImSdkRnModule.java
  android/src/main/java/com/openimsdkrn/listener/UploadLogProgressListener.java
  example/ios/Podfile.lock
  ios/OpenImSdkRn.m
  ios/UploadLogCallbackProxy.h
  ios/UploadLogCallbackProxy.m
Labels: size/L

#18 fix: fix uploadlog function
  example/ios/Podfile.lock
  ios/OpenImSdkRn.m
  ios/UploadLogCallbackProxy.m
Labels: size/S
